accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'

urlpatterns = [

    path('login/', views.login_user, name='login'),
    path('success/', views.success_page, name='success'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

]

contact/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

app_name = 'contact'

urlpatterns = [
    path("", views.ContactUsView.as_view(), name="contact", ),
    path("about-us/", TemplateView.as_view(template_name="contact/about_us.html"), name="about_us", ),
    path("pricing/", TemplateView.as_view(template_name="contact/pricing.html"), name="pricing", ),

]

digi/urls.py
from django.contrib import admin

from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('accounts/', include("accounts.urls")),
    path('contact/', include("contact.urls")),

]

accounts/models.py
from django.db import models


# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm as DjangoUserChangeForm,PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    first_name = forms.CharField(label='', max_length=55,
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label='', max_length=55,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].label = ''
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = ''


class UserChangeForm(DjangoUserChangeForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=55, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=55, widget=forms.TextInput(attrs={'class': 'form-control', }))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].help_text = ''

contact/forms.py
from django import forms
from django.core.mail import  send_mail

import logging

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "galavu10gmail.com",
            ["galavu10gmail.com"],
            fail_silently=False,
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from .forms import SignUpForm, UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, permission_required


def success_page(request):
    return render(request, 'test.html', {})


def logout_user(request):
    logout(request)
    messages.success(request, 'You have been logged out....')
    return redirect('index')


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You Have Successfully Logged In')
            return redirect('index')

        else:
            messages.success(request, 'Error Logging In - Try again....')
            return redirect('accounts:login')
    else:

        return render(request, 'accounts/login.html', {})


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You Have Successfully Registered. Please Login to Proceed')
            return redirect('accounts:login')

    else:
        form = SignUpForm()

    return render(request, 'accounts/register.html', {'form': form})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = SignUpForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'You Have Successfully Updated Your Profile')
            return redirect('index')
    else:
        form = UserChangeForm(instance=request.user)

    return render(request, 'accounts/edit_profile.html', {'form': form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'You Have Successfully Updated Your Password')
            return redirect('index')
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, 'accounts/change_password.html', {'form': form})

contact/views.py
from django.views.generic.edit import FormView
from . import forms
import logging
from django.contrib.auth import login, authenticate
from django.contrib import messages

logger = logging.getLogger(__name__)


class ContactUsView(FormView):
    template_name = "contact/contacts.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

accounts/templates/accounts/change_password.html
{% extends "base1.html" %}

{% block content %}
    <h2 class="text-center">Please fill the form below.</h2>
 <div class="col-md-6 offset-md-3">
         <form method="POST" action="{% url 'accounts:change_password' %}">
             {% csrf_token %}

             {% if form.errors %}
                 <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <small><sup>x</sup></small>
              </button>
              {% for field in form %}
                  {% if field.errors %}
                      {{ field.errors }}
                  {% endif %}
                 {% endfor %}
          </div>

             {% endif %}
             {{ form.as_p }}

             <button type="submit" class="btn btn-warning">Change Password</button>

         </form>
     </div>
{% endblock content %}

accounts/templates/accounts/edit_profile.html
{% extends "base1.html" %}
{% block content %}
    <h2 class="text-center">Please fill the form below.</h2>
 <div class="col-md-6 offset-md-3">
         <form method="POST" action="{% url 'accounts:edit_profile' %}">
             {% csrf_token %}
             {% if form.errors %}
                 <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <small><sup>x</sup></small>
              </button>
              {% for field in form %}
                  {% if field.errors %}
                      {{ field.errors }}
                  {% endif %}
                 {% endfor %}
          </div>

             {% endif %}
             {{ form.as_p }}
             <button type="submit" class="btn btn-danger">Submit</button>
         </form>
     </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base1.html' %}

{% block content %}
   <div class="col-md-6 offset-md-3">
       <h2>Login</h2>
    <p>Please fill the form below.</p>
    <form method="POST">
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.username.label_tag }}
            <input type="text" class="form-control{% if form.username.errors %}is-invalid{% endif %}"
                   id="id_username"
                   name="username"
                   placeholder="Your Username" value="{{ form.username.value|default:"" }}">
            {% if form.username.errors %}
                <div class="invalid-feedback">
                    {{ form.username.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            <input
                    type="password"
                    class="form-control{% if form.password.errors %}is-invalid{% endif %}"
                    id="id_password"
                    name="password"
                    placeholder="Your Password"
                    value="{{ form.password.value|default:"" }}">
            {% if form.password.errors %}
                <div class="invalid-feedback">
                    {{ form.password.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
   <p><small><a href="{% url 'accounts:change_password' %}">click here</a>To change Your Password</small></p>
    </div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base1.html" %}
{% block content %}
    <h2 class="text-center">Please fill the form below.</h2>
     <div class="col-md-6 offset-md-3">
         <form method="POST" action="{% url 'accounts:register' %}">
             {% csrf_token %}
             {% if form.errors %}
                 <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <small><sup>x</sup></small>
              </button>
              {% for field in form %}
                  {% if field.errors %}
                      {{ field.errors }}
                  {% endif %}
                 {% endfor %}
          </div>

             {% endif %}
             {{ form.as_p }}
             <button type="submit" class="btn btn-success">Register</button>
         </form>
     </div>
{% endblock content %}

contact/templates/contact/about_us.html
{% extends "base1.html" %}
{% block content %}
  <h2>About us</h2>
  
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>

{% endblock content %}

contact/templates/contact/contacts.html
{% extends "base1.html" %}
{% block content %}

<h2>Contact us</h2>
  <p>Please fill the form below to contact us</p>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text"
                   class="form-control{% if form.name.errors %}is-invalid{% endif %}"
                   id="id_name"
                   name="name"
                   placeholder="Your name"
                   value="{{ form.name.value|default:"" }}" >
            {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}
            <textarea
                    class="form-control {% if form.message.errors %}is-invalid{% endif %}"
                    id="id_message"
                    name="message"
                    rows="3">
                {{ form.message.value|default:""}}
            </textarea>
            {% if form.message.errors %}
                <div class="invalid-feedback">
                    {{ form.message.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>


  </div>
{% endblock content %}

contact/templates/contact/pricing.html
{% load staticfiles %}
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Pricing example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >


    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>10 users included</li>
          <li>2 GB of storage</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>10 GB of storage</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

templates/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Main </title>
  <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href=" {% static 'css/heroic-features.css' %}" rel="stylesheet">
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Digitext</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span>
            </a>

            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Manage Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                      <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout </a>
                    </div>
                </li>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:about_us' %}">About Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Drop
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a>
                      <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'contact:pricing' %}">Pricing</a>
                    </div>
                </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <small><sup>x</sup></small>
              </button>
              {{ message }}
          </div>
      {% endfor %}
  {% endif %}


<br>
  <div class="container">
      {% block content %}
      {% endblock %}
  </div>

  <br>
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Digitex 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{%static  'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%static  'vendor/cour/cour.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/index.html
{% extends "base1.html" %}
{% load static %}
{% block content %}


      <div class="bd-example">
          <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'image/laptop.jpeg' %}" class="d-block w-100" height="400" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h5>First slide label</h5>
                  <h1 class="display-3"> {% if user.is_authenticated %} <p>Welcome, {{ user.username }}. Thanks for logging in.</p> {% else %} <p>Welcome, new user. Please log in.</p> {% endif %}</h1>
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static 'image/ingine.jpeg' %}" class="d-block w-100" height="400"alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Second slide label</h5>
                  <h1 class="display-3"> {% if user.is_authenticated %} <p>Welcome, {{ user.username }}. Thanks for logging in.</p> {% else %} <p>Welcome, new user. Please log in.</p> {% endif %}</h1>
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static 'image/tatu.jpeg' %}" class="d-block w-100" height="400" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Third slide label</h5>
                  <h1 class="display-3"> {% if user.is_authenticated %} <p>Welcome, {{ user.username }}. Thanks for logging in.</p> {% else %} <p>Welcome, new user. Please log in.</p> {% endif %}</h1>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
    <br>
    <div class="row text-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

      

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

{% endblock content %}

templates/test.html
{% extends "base1.html" %}
{% block content %}
    <h2>You have successfully Logged in </h2>
{% endblock content %}